# Generated by Django 6.0.6 on 2026-07-02 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_usernotificationsettings'),
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(choices=[('WELCOME', 'Welcome Message'), ('THANK_YOU', 'Thank You Message'), ('FOLLOW_UP_1', 'Follow-up #1'), ('FOLLOW_UP_2', 'Follow-up #2'), ('FOLLOW_UP_3', 'Follow-up #3'), ('APPOINTMENT_CONFIRMATION', 'Appointment Confirmation'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('QUOTATION', 'Quotation Message'), ('INVOICE', 'Invoice Message'), ('ORDER_CONFIRMATION', 'Order Confirmation'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('MISSED_CALL', 'Missed Call Reply'), ('OUT_OF_OFFICE', 'Out of Office'), ('BUSINESS_HOURS', 'Business Hours'), ('FEEDBACK_REQUEST', 'Feedback Request'), ('REVIEW_REQUEST', 'Review Request'), ('CUSTOM', 'Custom')], db_index=True, max_length=40)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='messagetemplate',
            name='unique_message_template',
        ),
        migrations.AddField(
            model_name='staticmessagetemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='business.organization'),
        ),
        migrations.AddField(
            model_name='staticmessagetemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='organization',
        ),
        migrations.AddConstraint(
            model_name='staticmessagetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'user', 'template_type'), name='unique_static_template'),
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
    ]
