# Generated by Django 6.0.6 on 2026-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_freetrailphonenumber_twilioconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetrailphonenumber',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
