# Generated by Django 6.0.6 on 2026-07-13 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_freetrailphonenumber_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetrailphonenumber',
            name='messaging_service_sid',
        ),
        migrations.RemoveField(
            model_name='twilioconfiguration',
            name='master_account_auth_token',
        ),
        migrations.RemoveField(
            model_name='twilioconfiguration',
            name='master_account_sid',
        ),
        migrations.RemoveField(
            model_name='twilioconfiguration',
            name='trial_account_auth_token',
        ),
        migrations.RemoveField(
            model_name='twilioconfiguration',
            name='trial_account_name',
        ),
        migrations.RemoveField(
            model_name='twilioconfiguration',
            name='trial_account_sid',
        ),
        migrations.AddField(
            model_name='freetrailphonenumber',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='freetrailphonenumber',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freetrailphonenumber',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freetrailphonenumber',
            name='last_synced_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
