# Generated by Django 6.0.6 on 2026-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_freetrailphonenumber_messaging_service_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioconfiguration',
            name='master_account_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twilioconfiguration',
            name='master_account_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='twilioconfiguration',
            name='trial_account_auth_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='twilioconfiguration',
            name='trial_account_name',
            field=models.CharField(blank=True, default='Trial Pool', max_length=255),
        ),
        migrations.AddField(
            model_name='twilioconfiguration',
            name='trial_account_sid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
