# Generated by Django 6.0.6 on 2026-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_twilioconfiguration_master_account_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetrailphonenumber',
            name='number_type',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('TOLL_FREE', 'Toll Free')], default='TOLL_FREE', max_length=20),
        ),
    ]
