# Generated by Django 6.0.6 on 2026-07-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_freetrailphonenumber_number_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
