# Generated by Django 6.0.6 on 2026-07-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_twiliowebhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliowebhooklog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='twiliowebhooklog',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
