# Generated by Django 6.0.6 on 2026-07-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_twiliowebhooklog_method_twiliowebhooklog_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioconfiguration',
            name='event_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilioconfiguration',
            name='fallback_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
