# Generated by Django 6.0.6 on 2026-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='ai_request_limit',
            new_name='ai_reply_limit',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='advanced_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_auto_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='bulk_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_welcome_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='lead_scoring',
            field=models.BooleanField(default=False),
        ),
    ]
