# Generated by Django 6.0.6 on 2026-07-02 06:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_ai_request_limit_subscriptionplan_ai_reply_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='slug',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
