# Generated by Django 6.0.6 on 2026-07-02 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_usersubscription_user_alter_usersubscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='uuid',
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_info', to='subscription.payment'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
