# Generated by Django 6.0.6 on 2026-07-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_info', to='subscription.payment'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('awaiting_payment', 'Awaiting Payment'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended')], db_index=True, default='awaiting_payment', max_length=20),
        ),
    ]
