# Generated by Django 6.0.6 on 2026-07-01 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('login_method', models.CharField(choices=[('PASSWORD', 'Password'), ('OTP', 'OTP'), ('EMAIL_OTP', 'Email OTP'), ('GOOGLE', 'Google'), ('APPLE', 'Apple'), ('FACEBOOK', 'Facebook'), ('BIOMETRIC', 'Biometric')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('LOCKED', 'Locked'), ('EXPIRED', 'Expired'), ('INVALID_OTP', 'Invalid OTP'), ('INVALID_PASSWORD', 'Invalid Password')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('otp_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'Register'), ('PASSWORD_RESET', 'Password Reset'), ('PHONE_VERIFY', 'Phone Verification'), ('EMAIL_VERIFY', 'Email Verification')], max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_verifications',
                'indexes': [models.Index(fields=['user'], name='otp_verific_user_id_34905b_idx'), models.Index(fields=['phone_number'], name='otp_verific_phone_n_409331_idx'), models.Index(fields=['purpose'], name='otp_verific_purpose_7dae9c_idx'), models.Index(fields=['expires_at'], name='otp_verific_expires_e91cd1_idx')],
            },
        ),
    ]
