# Generated by Django 6.0.6 on 2026-07-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
