# Generated by Django 6.0.6 on 2026-07-01 04:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logo/')),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('BD', 'Bangladesh')], db_index=True, default='US', max_length=2)),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('AGENCY', 'Agency'), ('STORE', 'Store'), ('CLINIC', 'Clinic'), ('RESTAURANT', 'Restaurant'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], db_index=True, default='COMPANY', max_length=30)),
                ('industry', models.CharField(blank=True, choices=[('AUTOMOTIVE', 'Automotive'), ('REAL_ESTATE', 'Real Estate'), ('HEALTHCARE', 'Healthcare'), ('LEGAL', 'Legal'), ('FINANCE', 'Finance'), ('INSURANCE', 'Insurance'), ('HOME_SERVICE', 'Home Service'), ('BEAUTY', 'Beauty'), ('EDUCATION', 'Education'), ('ECOMMERCE', 'E-Commerce'), ('RESTAURANT', 'Restaurant'), ('TRAVEL', 'Travel'), ('SOFTWARE', 'Software'), ('MARKETING', 'Marketing'), ('CONSULTING', 'Consulting'), ('OTHER', 'Other')], db_index=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Weekly business working hours.')),
                ('is_verified', models.BooleanField(default=False, help_text='Organization verification status.')),
                ('is_demo', models.BooleanField(default=False, help_text='Used for demo/testing organizations.')),
                ('is_onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_step', models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('PROFILE_COMPLETED', 'Profile Completed'), ('NUMBER_ASSIGNED', 'Number Assigned'), ('AI_CONFIGURED', 'Ai Configured'), ('COMPLETED', 'Completed')], default='ACCOUNT_CREATED', max_length=50)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German')], default='EN', max_length=10)),
                ('timezone', models.CharField(default='America/New_York', max_length=100)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('CAD', 'Canadian Dollar'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('BDT', 'Bangladeshi Taka')], default='USD', max_length=10)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=20)),
                ('time_format', models.CharField(choices=[('12H', '12 Hours'), ('24H', '24 Hours')], default='12H', max_length=10)),
                ('lead_hot_score', models.PositiveSmallIntegerField(default=80, help_text='Minimum AI score to consider a lead as HOT.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('reply_tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual')], default='friendly', max_length=50)),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('reply_speed', models.PositiveBigIntegerField(default=0)),
                ('auto_follow_up', models.BooleanField(default=True)),
                ('push_notification_enabled', models.BooleanField(default=True)),
                ('email_notification_enabled', models.BooleanField(default=True)),
                ('notification_sound', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='business.organization')),
            ],
            options={
                'verbose_name': 'Business Setting',
                'verbose_name_plural': 'Business Settings',
                'db_table': 'business_settings',
                'ordering': ['organization__name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='business.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=30)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='business.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('TWILIO', 'Twilio')], db_index=True, default='TWILIO', max_length=20)),
                ('account_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('friendly_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled'), ('pending', 'Pending'), ('failed', 'Failed')], default='active', max_length=20)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_account', to='business.organization')),
            ],
            options={
                'db_table': 'provider_accounts',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('provider_phone_sid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('messaging_service_sid', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('RELEASED', 'Released'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='business.organization')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.provideraccount')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'db_table': 'business_phone_numbers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner'], name='org_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_verified'], name='org_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_onboarding_completed'], name='org_onboarding_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_organization_owner'),
        ),
        migrations.AddIndex(
            model_name='businesssetting',
            index=models.Index(fields=['language'], name='bs_language_idx'),
        ),
        migrations.AddIndex(
            model_name='businesssetting',
            index=models.Index(fields=['currency'], name='bs_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='businesssetting',
            index=models.Index(fields=['auto_reply_enabled'], name='bs_auto_reply_idx'),
        ),
        migrations.AddIndex(
            model_name='provideraccount',
            index=models.Index(fields=['provider', 'status'], name='provider_status_idx'),
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['organization', 'status'], name='phone_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['provider', 'provider_phone_sid'], name='phone_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['country'], name='phone_country_idx'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('organization', 'is_primary'), name='unique_primary_phone_per_org'),
        ),
    ]
