# Generated by Django 6.0.6 on 2026-07-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businesssetting_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='support_email',
        ),
    ]
