# Generated by Django 6.0.6 on 2026-07-02 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_organization_support_email'),
        ('core', '0002_businesstype_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.businesstype'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.industry'),
        ),
    ]
