# Generated by Django 6.0.6 on 2026-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_organization_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssetting',
            name='reply_tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual')], default='friendly', help_text='Tone of AI-generated replies. (e.g., friendly, professional, casual)', max_length=50),
        ),
    ]
