# Generated by Django 6.0.6 on 2026-07-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_usernotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideraccount',
            name='owner_account_sid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
