# Generated by Django 6.0.6 on 2026-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_provideraccount_owner_account_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideraccount',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
