# Generated by Django 6.0.6 on 2026-07-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_provideraccount_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTrailPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_account_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('account_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('account_auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('phone_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('provider_phone_sid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('messaging_service_sid', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('RELEASED', 'Released'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FreeTrailDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trail_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_phone_numbers', to='business.organization')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trail_phone_numbers', to='business.provideraccount')),
                ('free_trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.freetrailphonenumber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
