# Generated by Django 6.0.6 on 2026-07-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_freetrailphonenumber_alter_phonenumber_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetraildetails',
            name='free_trail',
        ),
        migrations.RemoveField(
            model_name='freetraildetails',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='freetraildetails',
            name='provider',
        ),
        migrations.DeleteModel(
            name='FreeTrailPhoneNumber',
        ),
        migrations.DeleteModel(
            name='FreeTrailDetails',
        ),
    ]
