# Generated by Django 6.0.6 on 2026-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_freetraildetails_free_trail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
