# Generated by Django 6.0.6 on 2026-07-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_phonenumber_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='messaging_service_sid',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
