# Generated by Django 6.0.6 on 2026-07-01 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(db_index=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('hot', 'Hot'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_incoming_at', models.DateTimeField(blank=True, null=True)),
                ('last_outgoing_at', models.DateTimeField(blank=True, null=True)),
                ('last_ai_reply_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business_phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='business.phonenumber')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='business.organization')),
            ],
            options={
                'db_table': 'crm_leads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('message_received', 'Message Received'), ('message_sent', 'Message Sent'), ('ai_replied', 'AI Replied'), ('stage_changed', 'Stage Changed'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('handoff', 'Handoff'), ('note_added', 'Note Added')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'db_table': 'crm_lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='crm.lead')),
            ],
            options={
                'db_table': 'crm_lead_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_ai', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='crm.lead')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments', to='crm.leadtag')),
            ],
            options={
                'db_table': 'crm_lead_tag_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'contact_number'], name='crm_leads_organiz_291767_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage'], name='crm_leads_stage_0a3e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['score'], name='crm_leads_score_4979f3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_message_at'], name='crm_leads_last_me_c42d0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'contact_number'), name='unique_lead_per_organization'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead'], name='crm_lead_ac_lead_id_3cb6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['activity_type'], name='crm_lead_ac_activit_ca2e7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadtag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('lead', 'name'), name='unique_lead_tag'),
        ),
        migrations.AddIndex(
            model_name='leadtagassignment',
            index=models.Index(fields=['lead'], name='crm_lead_ta_lead_id_3250b9_idx'),
        ),
        migrations.AddIndex(
            model_name='leadtagassignment',
            index=models.Index(fields=['tag'], name='crm_lead_ta_tag_id_e99073_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadtagassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('lead', 'tag'), name='unique_tag_assignment'),
        ),
    ]
